# @package _global_
defaults:
  - /benchmark/nav/objectnav/objectnav_hssd-hab.yaml
  - /habitat/task/measurements: 
    - top_down_map
  - _self_

habitat:
  dataset:
    type: ObjectNav-v1
    split: val
    data_path: data/datasets/objectnav/hssd-hab/{split}/{split}.json.gz
    scenes_dir: data/scene_datasets/hssd-hab/scenes
    content_scenes: ["*"]

DATA_GEN:
  seed: 0
  min_pixel_area: 1000
  frame_height: 480
  frame_width: 640
  meters_per_grid_pixel: 0.05
  viewpoint_spacing: 0.5
  turn_angle: 30
  num_samples: 100
  num_scenes: 1
  dataset:
    data_root: data_od/
    dataset_name: hssd_od_openvoc