# @package _global_
defaults:
  - /benchmark/nav/objectnav/objectnav_hssd-hab.yaml
  - _self_

habitat:
  dataset:
    type: ObjectNav-v1
    split: val
    data_path: data/datasets/objectnav/hssd-hab/{split}/{split}.json.gz
    scenes_dir: data/scene_datasets/hssd-hab/scenes
    content_scenes: ["*"]
  task:
    measurements:
      top_down_map:
        type: TopDownMap
        map_resolution: 1024
        draw_source: true
        draw_border: true
        draw_shortest_path: true
        draw_view_points: true

HABITAT_OD:
  data_root: data_od/
  dataset_name: hssd_od_openvoc
  seed: 0
  min_pixel_area: 1000
  frame_height: 480
  frame_width: 640
  meters_per_grid_pixel: 0.25
  turn_angle: 30
  num_samples: 100
  num_scenes: 1
