# @package _global_
defaults:
  - /habitat: habitat_config_base
  - /habitat/task: pointnav
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbd_agent
  - _self_

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    scene_dataset: "data/scene_datasets/hssd-hab/hssd-hab.scene_dataset_config.json"
    navmesh_include_static_objects: True
    turn_angle: 30
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 0.88, 0]
          depth_sensor:
            width: 640
            height: 480
            hfov: 79
            min_depth: 0.5
            max_depth: 5.0
            position: [0, 0.88, 0]
        height: 0.88
        radius: 0.18
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: False
  dataset:
    type: PointNav-v1
    split: val
    data_path: data/datasets/habitat_active_od/{split}/{split}.json.gz
    scenes_dir: data/scene_datasets/hssd-hab/scenes
    content_scenes: ["*"]


HABITAT_ACTIVE_OD:
  data_root: data_od/
  seed: 0
  frame_height: 480
  frame_width: 640
  min_pixel_area: 1000
  meters_per_grid_pixel: 0.25
  turn_angle: 30
  num_samples: 100
  num_scenes: 1


AGENT:
  NUM_ENVIRONMENTS: 1      # number of environments (per agent process)
  DUMP_LOCATION: datadump   # path to dump models and log
  EXP_NAME: debug   # experiment name
  PRINT_IMAGES: 1           # 1: save visualization as images, 0: no image saving
  VERBOSE: True

  SEMANTIC_MAP:
    map_size_cm: 4800                 # global map size (in centimeters)
    map_resolution: 5                 # size of map bins (in centimeters)
    vision_range: 100                 # diameter of local map region visible by the agent (in cells)
    explored_radius: 50              # radius (in centimeters) of visually explored region
    been_close_to_radius: 200         # radius (in centimeters) of been close to region
    global_downscaling: 2             # ratio of global over local map
    du_scale: 4                       # frame downscaling before projecting to point cloud
    cat_pred_threshold: 5.0           # number of depth points to be in bin to classify it as a certain semantic category
    exp_pred_threshold: 1.0           # number of depth points to be in bin to consider it as explored
    map_pred_threshold: 1.0           # number of depth points to be in bin to consider it as obstacle
    num_sem_categories: 1
    must_explore_close: False
    min_obs_height_cm: 30             # minimum height (in centimeters) of obstacle to be considered as obstacle
    # erosion and filtering to reduce the number of spurious artifacts
    dilate_obstacles: False
    dilate_size: 3
    dilate_iter: 1

  SEMANTIC_PREDICTION:
    depth_filtering: True
    depth_filter_range_cm: 0        # 1m about the depth median (+/- 50cm)
    goal_filtering: True              # filter out outlier points in the goal map w/ DBSCAN